apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app: {{ .Release.Name }}-redis
    pipeline_id: {{ .Values.info.pipeline_id | quote }}
    build_id: {{ .Values.info.build_id | quote }}
spec:
  replicas: 1
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-redis
    spec:
      imagePullSecrets:
      - name: gitlab-registry
      containers:
      - name: redis
        image: redis
        ports:
        - name: redis
          containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app: {{ .Release.Name }}-redis
    pipeline_id: {{ .Values.info.pipeline_id | quote }}
    build_id: {{ .Values.info.build_id | quote }}
spec:
  ports:
  - name: redis
    port: 6379
  selector:
    app: {{ .Release.Name }}-redis
